<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/LightDraw.Desktop/LightDraw.Desktop.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
  </ItemGroup>
</Project>
