<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../LightDraw.Core/LightDraw.Core.csproj" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Skia" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="LightDraw.Tests" />
  </ItemGroup>
</Project>
